// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.xgene.protobuf;

public final class StockTickOuterClass {
  private StockTickOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StockTickOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StockTick)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stockId = 1;</code>
     */
    java.lang.String getStockId();
    /**
     * <code>string stockId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStockIdBytes();

    /**
     * <code>int32 price = 2;</code>
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code StockTick}
   */
  public  static final class StockTick extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StockTick)
      StockTickOrBuilder {
    // Use StockTick.newBuilder() to construct.
    private StockTick(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockTick() {
      stockId_ = "";
      price_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StockTick(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stockId_ = s;
              break;
            }
            case 16: {

              price_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xgene.protobuf.StockTickOuterClass.internal_static_StockTick_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xgene.protobuf.StockTickOuterClass.internal_static_StockTick_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xgene.protobuf.StockTickOuterClass.StockTick.class, com.xgene.protobuf.StockTickOuterClass.StockTick.Builder.class);
    }

    public static final int STOCKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object stockId_;
    /**
     * <code>string stockId = 1;</code>
     */
    public java.lang.String getStockId() {
      java.lang.Object ref = stockId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockId_ = s;
        return s;
      }
    }
    /**
     * <code>string stockId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStockIdBytes() {
      java.lang.Object ref = stockId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    /**
     * <code>int32 price = 2;</code>
     */
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStockIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stockId_);
      }
      if (price_ != 0) {
        output.writeInt32(2, price_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStockIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stockId_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xgene.protobuf.StockTickOuterClass.StockTick)) {
        return super.equals(obj);
      }
      com.xgene.protobuf.StockTickOuterClass.StockTick other = (com.xgene.protobuf.StockTickOuterClass.StockTick) obj;

      boolean result = true;
      result = result && getStockId()
          .equals(other.getStockId());
      result = result && (getPrice()
          == other.getPrice());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getStockId().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xgene.protobuf.StockTickOuterClass.StockTick parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xgene.protobuf.StockTickOuterClass.StockTick prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StockTick}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StockTick)
        com.xgene.protobuf.StockTickOuterClass.StockTickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xgene.protobuf.StockTickOuterClass.internal_static_StockTick_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xgene.protobuf.StockTickOuterClass.internal_static_StockTick_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xgene.protobuf.StockTickOuterClass.StockTick.class, com.xgene.protobuf.StockTickOuterClass.StockTick.Builder.class);
      }

      // Construct using com.xgene.protobuf.StockTickOuterClass.StockTick.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stockId_ = "";

        price_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xgene.protobuf.StockTickOuterClass.internal_static_StockTick_descriptor;
      }

      public com.xgene.protobuf.StockTickOuterClass.StockTick getDefaultInstanceForType() {
        return com.xgene.protobuf.StockTickOuterClass.StockTick.getDefaultInstance();
      }

      public com.xgene.protobuf.StockTickOuterClass.StockTick build() {
        com.xgene.protobuf.StockTickOuterClass.StockTick result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xgene.protobuf.StockTickOuterClass.StockTick buildPartial() {
        com.xgene.protobuf.StockTickOuterClass.StockTick result = new com.xgene.protobuf.StockTickOuterClass.StockTick(this);
        result.stockId_ = stockId_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xgene.protobuf.StockTickOuterClass.StockTick) {
          return mergeFrom((com.xgene.protobuf.StockTickOuterClass.StockTick)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xgene.protobuf.StockTickOuterClass.StockTick other) {
        if (other == com.xgene.protobuf.StockTickOuterClass.StockTick.getDefaultInstance()) return this;
        if (!other.getStockId().isEmpty()) {
          stockId_ = other.stockId_;
          onChanged();
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xgene.protobuf.StockTickOuterClass.StockTick parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xgene.protobuf.StockTickOuterClass.StockTick) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object stockId_ = "";
      /**
       * <code>string stockId = 1;</code>
       */
      public java.lang.String getStockId() {
        java.lang.Object ref = stockId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stockId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStockIdBytes() {
        java.lang.Object ref = stockId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stockId = 1;</code>
       */
      public Builder setStockId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stockId = 1;</code>
       */
      public Builder clearStockId() {
        
        stockId_ = getDefaultInstance().getStockId();
        onChanged();
        return this;
      }
      /**
       * <code>string stockId = 1;</code>
       */
      public Builder setStockIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockId_ = value;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>int32 price = 2;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>int32 price = 2;</code>
       */
      public Builder setPrice(int value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price = 2;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StockTick)
    }

    // @@protoc_insertion_point(class_scope:StockTick)
    private static final com.xgene.protobuf.StockTickOuterClass.StockTick DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xgene.protobuf.StockTickOuterClass.StockTick();
    }

    public static com.xgene.protobuf.StockTickOuterClass.StockTick getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockTick>
        PARSER = new com.google.protobuf.AbstractParser<StockTick>() {
      public StockTick parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StockTick(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockTick> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockTick> getParserForType() {
      return PARSER;
    }

    public com.xgene.protobuf.StockTickOuterClass.StockTick getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockTick_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockTick_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\"+\n\tStockTick\022\017\n\007stockId\030\001 \001" +
      "(\t\022\r\n\005price\030\002 \001(\005B)\n\022com.xgene.protobufB" +
      "\023StockTickOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StockTick_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockTick_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockTick_descriptor,
        new java.lang.String[] { "StockId", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
